# SpineNet-190 + RetinaNet:
# - 52.0% mAP with init_drop_connect_rate: 0.2, activation: 'swish'
architecture:
  backbone: 'spinenet'
  multilevel_features: 'identity'
train:
  total_steps: 185200
  train_batch_size: 256
  learning_rate:
    warmup_steps: 2000
    init_learning_rate: 0.3
    learning_rate_levels: [0.03, 0.003]
    learning_rate_steps: [171310, 180570]
  l2_weight_decay: 0.00004
  gradient_clip_norm: 10.0
batch_norm_activation:
  use_sync_bn: true
  activation: 'swish'
spinenet:
  model_id: '190'
  init_drop_connect_rate: 0.2
retinanet_head:
  num_filters: 512
  num_convs: 7
retinanet_parser:
  output_size: [1280, 1280]
  aug_scale_min: 0.1
  aug_scale_max: 1.9
