# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/datum.proto
"""Generated protocol buffer code."""
from npu_bridge.npu_init import *
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/datum.proto',
  package='protos',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12protos/datum.proto\x12\x06protos\"\x1d\n\nDatumShape\x12\x0f\n\x03\x64im\x18\x01 \x03(\x03\x42\x02\x10\x01\"\x1e\n\tFloatList\x12\x11\n\x05value\x18\x01 \x03(\x02\x42\x02\x10\x01\"\x1f\n\nUint32List\x12\x11\n\x05value\x18\x01 \x03(\rB\x02\x10\x01\"\x91\x01\n\nDatumProto\x12!\n\x05shape\x18\x01 \x01(\x0b\x32\x12.protos.DatumShape\x12\'\n\nfloat_list\x18\x02 \x01(\x0b\x32\x11.protos.FloatListH\x00\x12)\n\x0buint32_list\x18\x03 \x01(\x0b\x32\x12.protos.Uint32ListH\x00\x42\x0c\n\nkind_oneof\"W\n\x0e\x44\x61tumPairProto\x12!\n\x05\x66irst\x18\x01 \x01(\x0b\x32\x12.protos.DatumProto\x12\"\n\x06second\x18\x02 \x01(\x0b\x32\x12.protos.DatumProto'
)




_DATUMSHAPE = _descriptor.Descriptor(
  name='DatumShape',
  full_name='protos.DatumShape',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dim', full_name='protos.DatumShape.dim', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=59,
)


_FLOATLIST = _descriptor.Descriptor(
  name='FloatList',
  full_name='protos.FloatList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='protos.FloatList.value', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=91,
)


_UINT32LIST = _descriptor.Descriptor(
  name='Uint32List',
  full_name='protos.Uint32List',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='protos.Uint32List.value', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=124,
)


_DATUMPROTO = _descriptor.Descriptor(
  name='DatumProto',
  full_name='protos.DatumProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape', full_name='protos.DatumProto.shape', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='float_list', full_name='protos.DatumProto.float_list', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uint32_list', full_name='protos.DatumProto.uint32_list', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='kind_oneof', full_name='protos.DatumProto.kind_oneof',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=127,
  serialized_end=272,
)


_DATUMPAIRPROTO = _descriptor.Descriptor(
  name='DatumPairProto',
  full_name='protos.DatumPairProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='first', full_name='protos.DatumPairProto.first', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='second', full_name='protos.DatumPairProto.second', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=361,
)

_DATUMPROTO.fields_by_name['shape'].message_type = _DATUMSHAPE
_DATUMPROTO.fields_by_name['float_list'].message_type = _FLOATLIST
_DATUMPROTO.fields_by_name['uint32_list'].message_type = _UINT32LIST
_DATUMPROTO.oneofs_by_name['kind_oneof'].fields.append(
  _DATUMPROTO.fields_by_name['float_list'])
_DATUMPROTO.fields_by_name['float_list'].containing_oneof = _DATUMPROTO.oneofs_by_name['kind_oneof']
_DATUMPROTO.oneofs_by_name['kind_oneof'].fields.append(
  _DATUMPROTO.fields_by_name['uint32_list'])
_DATUMPROTO.fields_by_name['uint32_list'].containing_oneof = _DATUMPROTO.oneofs_by_name['kind_oneof']
_DATUMPAIRPROTO.fields_by_name['first'].message_type = _DATUMPROTO
_DATUMPAIRPROTO.fields_by_name['second'].message_type = _DATUMPROTO
DESCRIPTOR.message_types_by_name['DatumShape'] = _DATUMSHAPE
DESCRIPTOR.message_types_by_name['FloatList'] = _FLOATLIST
DESCRIPTOR.message_types_by_name['Uint32List'] = _UINT32LIST
DESCRIPTOR.message_types_by_name['DatumProto'] = _DATUMPROTO
DESCRIPTOR.message_types_by_name['DatumPairProto'] = _DATUMPAIRPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DatumShape = _reflection.GeneratedProtocolMessageType('DatumShape', (_message.Message,), {
  'DESCRIPTOR' : _DATUMSHAPE,
  '__module__' : 'protos.datum_pb2'
  # @@protoc_insertion_point(class_scope:protos.DatumShape)
  })
_sym_db.RegisterMessage(DatumShape)

FloatList = _reflection.GeneratedProtocolMessageType('FloatList', (_message.Message,), {
  'DESCRIPTOR' : _FLOATLIST,
  '__module__' : 'protos.datum_pb2'
  # @@protoc_insertion_point(class_scope:protos.FloatList)
  })
_sym_db.RegisterMessage(FloatList)

Uint32List = _reflection.GeneratedProtocolMessageType('Uint32List', (_message.Message,), {
  'DESCRIPTOR' : _UINT32LIST,
  '__module__' : 'protos.datum_pb2'
  # @@protoc_insertion_point(class_scope:protos.Uint32List)
  })
_sym_db.RegisterMessage(Uint32List)

DatumProto = _reflection.GeneratedProtocolMessageType('DatumProto', (_message.Message,), {
  'DESCRIPTOR' : _DATUMPROTO,
  '__module__' : 'protos.datum_pb2'
  # @@protoc_insertion_point(class_scope:protos.DatumProto)
  })
_sym_db.RegisterMessage(DatumProto)

DatumPairProto = _reflection.GeneratedProtocolMessageType('DatumPairProto', (_message.Message,), {
  'DESCRIPTOR' : _DATUMPAIRPROTO,
  '__module__' : 'protos.datum_pb2'
  # @@protoc_insertion_point(class_scope:protos.DatumPairProto)
  })
_sym_db.RegisterMessage(DatumPairProto)


_DATUMSHAPE.fields_by_name['dim']._options = None
_FLOATLIST.fields_by_name['value']._options = None
_UINT32LIST.fields_by_name['value']._options = None
# @@protoc_insertion_point(module_scope)

