# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/feature.proto
"""Generated protocol buffer code."""
from npu_bridge.npu_init import *
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import datum_pb2 as protos_dot_datum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/feature.proto',
  package='protos',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14protos/feature.proto\x12\x06protos\x1a\x12protos/datum.proto\"\x81\x01\n\x0b\x44\x65lfFeature\x12&\n\ndescriptor\x18\x01 \x01(\x0b\x32\x12.protos.DatumProto\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\r\n\x05scale\x18\x04 \x01(\x02\x12\x13\n\x0borientation\x18\x05 \x01(\x02\x12\x10\n\x08strength\x18\x06 \x01(\x02\"4\n\x0c\x44\x65lfFeatures\x12$\n\x07\x66\x65\x61ture\x18\x01 \x03(\x0b\x32\x13.protos.DelfFeature'
  ,
  dependencies=[protos_dot_datum__pb2.DESCRIPTOR,])




_DELFFEATURE = _descriptor.Descriptor(
  name='DelfFeature',
  full_name='protos.DelfFeature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='descriptor', full_name='protos.DelfFeature.descriptor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='protos.DelfFeature.x', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='protos.DelfFeature.y', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scale', full_name='protos.DelfFeature.scale', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='protos.DelfFeature.orientation', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='strength', full_name='protos.DelfFeature.strength', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=182,
)


_DELFFEATURES = _descriptor.Descriptor(
  name='DelfFeatures',
  full_name='protos.DelfFeatures',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='feature', full_name='protos.DelfFeatures.feature', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=236,
)

_DELFFEATURE.fields_by_name['descriptor'].message_type = protos_dot_datum__pb2._DATUMPROTO
_DELFFEATURES.fields_by_name['feature'].message_type = _DELFFEATURE
DESCRIPTOR.message_types_by_name['DelfFeature'] = _DELFFEATURE
DESCRIPTOR.message_types_by_name['DelfFeatures'] = _DELFFEATURES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DelfFeature = _reflection.GeneratedProtocolMessageType('DelfFeature', (_message.Message,), {
  'DESCRIPTOR' : _DELFFEATURE,
  '__module__' : 'protos.feature_pb2'
  # @@protoc_insertion_point(class_scope:protos.DelfFeature)
  })
_sym_db.RegisterMessage(DelfFeature)

DelfFeatures = _reflection.GeneratedProtocolMessageType('DelfFeatures', (_message.Message,), {
  'DESCRIPTOR' : _DELFFEATURES,
  '__module__' : 'protos.feature_pb2'
  # @@protoc_insertion_point(class_scope:protos.DelfFeatures)
  })
_sym_db.RegisterMessage(DelfFeatures)


# @@protoc_insertion_point(module_scope)

