general:
    backend: tensorflow  # pytorch | tensorflow | mindspore
    parallel_search: False
    parallel_fully_train: False


pipeline: [random, mutate, fully_train]


random:
    pipe_step:
        type: SearchPipeStep

    dataset:
        type: DIV2K
        common:
            value_div: 255.0
        train:
            root_HR: /cache/datasets/DIV2K/div2k_train/hr
            root_LR: /cache/datasets/DIV2K/div2k_train/lr
            upscale: 2
            crop: 64    # crop size of lr image
            hflip: true    # flip image horizontally
            vflip: true    # flip image vertically
            rot90: true    # flip image diagonally
            shuffle: true
            num_workers: 2
            batch_size: 16
            pin_memory: false
        test:
            root_HR: /cache/datasets/DIV2K/div2k_valid/hr
            root_LR: /cache/datasets/DIV2K/div2k_valid/lr
            upscale: 2
            crop: 64
            pin_memory: false
    search_space:
        type: SearchSpace
        modules: ['custom']
        custom:
            type: MtMSR
            in_channel: 3
            out_channel: 3
            upscale: 2
            rgb_mean: [0.4040, 0.4371, 0.4488]
            candidates: [res2, res3]
            block_range: [10, 80]
            cib_range: [3, 4]

    search_algorithm:
        type: SRRandom
        codec: SRCodec
        policy:
            num_sample: 1

    trainer:
        type: Trainer
        epochs: 1
        optimizer:
            type: Adam
            params:
                lr: 0.0004
        lr_scheduler:
            type: MultiStepLR
            params:
                milestones: [100, 200]
                gamma: 0.5
        loss:
            type: L1Loss
        metric:
            type: PSNR
            params:
                scale: 2
        calc_params_each_epoch: True
        train_report_steps: 1

    evaluator:
        type: Evaluator
        host_evaluator:
            type: HostEvaluator
            metric:
                type: PSNR
            load_pkl: False


mutate:
    pipe_step:
        type: SearchPipeStep

    dataset:
        ref: random.dataset

    search_space:
        type: SearchSpace
        ref: random.search_space

    search_algorithm:
        type: SRMutate
        codec: SRCodec
        policy:
            num_mutate: 1
            num_sample: 1

    trainer:
        ref: random.trainer
        epochs: 1
        save_model_desc: True


fully_train:
    pipe_step:
        type: TrainPipeStep
        models_folder: "{local_base_path}/output/mutate/"
    dataset:
        ref: random.dataset
        train:
            batch_size: 50

    search_space:
        ref: random.search_space

    trainer:
        type: Trainer
        seed: 0
        epochs: 1
        optimizer:
            type: Adam
            params:
                lr: 0.0002
        lr_scheduler:
            type: StepLR
            params:
                step_size: 4000
                gamma: 0.5
        loss:
            type: L1Loss
        metric:
            type: PSNR
            params:
                scale: 2
